In [4]:
import warnings

import numpy as np  
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

from sklearn.preprocessing import StandardScaler, RobustScaler

# X와 y 데이터 셋 만들기
from sklearn.model_selection import train_test_split
# from sklearn.model_selection import StratifiedShuffleSplit
# from sklearn.model_selection import KFold, StratifiedKFold

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier

from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, recall_score
from imblearn.metrics import classification_report_imbalanced

In [1]:
# 2021-11-23

In [6]:
## 1. Data Load

In [7]:
get_ipython().run_line_magic('matplotlib', 'inline')
warnings.filterwarnings("ignore")
# 파일 불러오기
filepath = 'https://github.com/mchoimis/financialml/raw/main/fraud/'
DF = pd.read_csv(filepath + 'fraud.csv')
print(DF.shape)
DF.head()  

(284807, 31)


Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [9]:
### Missing 여부 확인하기
#DF.isnull().sum()
#### 모두 0인 것을 확인할 수 있다.

In [10]:
### 불러온 데이터의 클래스 분포 확인하기
#### 99.8% 정상, 0.1% 비정상 이다
DF.groupby(by=['Class']).count()
print('Target class is ', '{0:0.4f}'. format(492/(284315+492)*100), '%')

Target class is  0.1727 %


In [11]:
################################################################################
## 2. Preprocess
################################################################################
### 2.1 Normalized the Data
#### robust scaler를 사용하여 scale을 조정
# 데이터 스케일 조정하기
rob_scaler = RobustScaler() 
DF['scaled_amount'] = rob_scaler.fit_transform(DF['Amount'].values.reshape(-1,1))
DF['scaled_time'] = rob_scaler.fit_transform(DF['Time'].values.reshape(-1,1))
DF.drop(['Time','Amount'], axis=1, inplace=True)

scaled_amount = DF['scaled_amount']
scaled_time = DF['scaled_time']
DF.drop(['scaled_amount', 'scaled_time'], axis=1, inplace=True)
DF.insert(0, 'scaled_amount', scaled_amount)
DF.insert(1, 'scaled_time', scaled_time)
DF.head()

scaled_amount  scaled_time        V1  ...       V27       V28  Class
0       1.783274    -0.994983 -1.359807  ...  0.133558 -0.021053      0
1      -0.269825    -0.994983  1.191857  ... -0.008983  0.014724      0
2       4.983721    -0.994972 -1.358354  ... -0.055353 -0.059752      0
3       1.418291    -0.994972 -0.966272  ...  0.062723  0.061458      0
4       0.670579    -0.994960 -1.158233  ...  0.219422  0.215153      0

[5 rows x 31 columns]

In [ ]:
# 2.X undersampling 
#### target data 의 skew 정도가 매우 높기에 클래스 간 분포를 맞추는 것이 필요합니다.

In [22]:
DF = DF.sample(frac=1)
DF_1 = DF.loc[DF['Class'] == 1]
DF_0 = DF.loc[DF['Class'] == 0][:DF_1.shape[0]]
print(DF_0.shape, DF_1.shape)

(492, 31) (492, 31)


In [24]:
DF = pd.concat([DF_0, DF_1], axis = 0)
DF = DF.sample(frac = 1, random_state = 0)
DF.head()

scaled_amount  scaled_time        V1  ...       V27       V28  Class
114610      -0.153706    -0.130934 -1.810249  ... -0.138160 -0.037239      0
143336       3.226717     0.006967 -6.713407  ...  1.649906 -0.394905      1
241394      -0.097813     0.779109 -1.845963  ...  0.255659  0.156684      0
116139       0.767694    -0.123744 -1.548788  ...  0.625922  0.395573      1
154286      -0.294557     0.192190 -1.465316  ...  0.675525  0.424849      1

[5 rows x 31 columns]

In [36]:
# 3. Split the Data
X = DF.drop('Class', axis=1)
y = DF['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=.2,
                                                    random_state = 0,
                                                    stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(787, 30) (197, 30) (787,) (197,)


In [37]:
#### 데이터셋에서는 비율도 확인
print(y_train.value_counts()/y_train.shape *100)
print(y_test.value_counts()/y_test.shape *100)

1    50.063532
0    49.936468
Name: Class, dtype: float64
0    50.253807
1    49.746193
Name: Class, dtype: float64


In [38]:
# 모델 인풋에 들어가기 위한 데이터의 형태 바꾸기
xTrainNP = X_train.values
xTestNP  = X_test.values
yTrainNP = y_train.values
yTestNP  = y_test.values

In [39]:
# 학습시킬 모델 로드하기
classifiers = {
    "Logisitic Regression": LogisticRegression(),
    "K Nearest": KNeighborsClassifier(),
    "Support Vector Classifier": SVC(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Random Forest Classifier": RandomForestClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "LightGBM Classifier": LGBMClassifier()
}

In [40]:
# 모델별 cross validation 한 결과의 평균 정확도 점수 출력하기
for key, classifier in classifiers.items():
    classifier.fit(xTrainNP, yTrainNP)
    training_score = cross_val_score(classifier, xTrainNP, yTrainNP, cv=5)
    print(classifier.__class__.__name__, ':', round(training_score.mean(), 2) * 100, '% accuracy')

LogisticRegression : 94.0 % accuracy
KNeighborsClassifier : 92.0 % accuracy
SVC : 93.0 % accuracy
DecisionTreeClassifier : 89.0 % accuracy
RandomForestClassifier : 94.0 % accuracy
GradientBoostingClassifier : 93.0 % accuracy
LGBMClassifier : 94.0 % accuracy


In [42]:
from sklearn.metrics import accuracy_score, precision_score
from sklearn.metrics import recall_score, confusion_matrix

In [45]:
### 올바른 예

# 모델별 분류결과 확인하기 (올바른 예)
for key, classifier in classifiers.items():
    y_pred = classifier.predict(X_test)  ####
    results = classification_report(y_test, y_pred)  ####
    print(classifier.__class__.__name__, '-------','\n', results)

LogisticRegression ------- 
               precision    recall  f1-score   support

           0       0.91      0.97      0.94        99
           1       0.97      0.90      0.93        98

    accuracy                           0.93       197
   macro avg       0.94      0.93      0.93       197
weighted avg       0.94      0.93      0.93       197

KNeighborsClassifier ------- 
               precision    recall  f1-score   support

           0       0.91      0.97      0.94        99
           1       0.97      0.90      0.93        98

    accuracy                           0.93       197
   macro avg       0.94      0.93      0.93       197
weighted avg       0.94      0.93      0.93       197

SVC ------- 
               precision    recall  f1-score   support

           0       0.91      1.00      0.95        99
           1       1.00      0.90      0.95        98

    accuracy                           0.95       197
   macro avg       0.95      0.95      0.95       197


In [46]:
# 모델별 Confusion Matrix 확인하기 (올바른 예)
for key, classifier in classifiers.items():
    y_pred = classifier.predict(X_test) ####
    cm = confusion_matrix(y_test, y_pred)  ####
    print(classifier.__class__.__name__, '\n', cm, '\n')

LogisticRegression 
 [[96  3]
 [10 88]] 

KNeighborsClassifier 
 [[96  3]
 [10 88]] 

SVC 
 [[99  0]
 [10 88]] 

DecisionTreeClassifier 
 [[80 19]
 [10 88]] 

RandomForestClassifier 
 [[99  0]
 [12 86]] 

GradientBoostingClassifier 
 [[94  5]
 [11 87]] 

LGBMClassifier 
 [[94  5]
 [10 88]] 



In [47]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [49]:
def get_clf_eval(y_test, pred):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    print('오차행렬')
    print(confusion)
    print('정확도:{0:.4f}, 정밀도:{1:.4f}, 재현율:{2:.4f}'.format(accuracy,
                                                                    precision,
                                                                    recall))


In [50]:
get_clf_eval(y_test, y_pred)

오차행렬
[[94  5]
 [10 88]]
정확도:0.9239, 정밀도:0.9462, 재현율:0.8980


In [55]:
# 모델별 Confusion Matrix 확인하기 (올바른 예)
for key, classifier in classifiers.items():
    y_pred = classifier.predict(X_test) ####
    print(classifier.__class__.__name__)
    get_clf_eval(y_test, y_pred)
    print('\n')

LogisticRegression
오차행렬
[[96  3]
 [10 88]]
정확도:0.9340, 정밀도:0.9670, 재현율:0.8980


KNeighborsClassifier
오차행렬
[[96  3]
 [10 88]]
정확도:0.9340, 정밀도:0.9670, 재현율:0.8980


SVC
오차행렬
[[99  0]
 [10 88]]
정확도:0.9492, 정밀도:1.0000, 재현율:0.8980


DecisionTreeClassifier
오차행렬
[[80 19]
 [10 88]]
정확도:0.8528, 정밀도:0.8224, 재현율:0.8980


RandomForestClassifier
오차행렬
[[99  0]
 [12 86]]
정확도:0.9391, 정밀도:1.0000, 재현율:0.8776


GradientBoostingClassifier
오차행렬
[[94  5]
 [11 87]]
정확도:0.9188, 정밀도:0.9457, 재현율:0.8878


LGBMClassifier
오차행렬
[[94  5]
 [10 88]]
정확도:0.9239, 정밀도:0.9462, 재현율:0.8980


